version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_ListAssets_09_07Project
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277/KMAT_ListAssets_09_07Project
  gitUsername: lakshmidevi277
  gitBranch: main
- name: SalesforceRestTest1011
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: lakshmidevi277
  gitBranch: main
- name: SalesforceSoapTest1011
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: lakshmidevi277
  gitBranch: main
- name: SalesforceSoapTest1015
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: lakshmidevi277
  gitBranch: main
- name: SalesforceRestTest1015
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: lakshmidevi277
  gitBranch: main
- name: SalesforceSOAP_KMAT_Jul2024
  gitServerName: karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
